#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Builtin {
    Add,
    Subtract,
    Multiply,
    Divide,
    LessThan,
    GreaterThan,
    Equal,
    LessEqual,
    Not,
    Cons,
    Car,
    Cdr,
    Null,
    List,
    Length,
    StringPredicate,
    NumberPredicate,
    BooleanPredicate,
    PairPredicate,
    SymbolPredicate,
    Apply,
    CallCc,
}

pub(crate) const BUILTINS: [(&str, Builtin); 22] = [
    ("+", Builtin::Add),
    ("-", Builtin::Subtract),
    ("*", Builtin::Multiply),
    ("/", Builtin::Divide),
    ("<", Builtin::LessThan),
    (">", Builtin::GreaterThan),
    ("=", Builtin::Equal),
    ("<=", Builtin::LessEqual),
    ("not", Builtin::Not),
    ("cons", Builtin::Cons),
    ("car", Builtin::Car),
    ("cdr", Builtin::Cdr),
    ("null?", Builtin::Null),
    ("list", Builtin::List),
    ("length", Builtin::Length),
    ("string?", Builtin::StringPredicate),
    ("number?", Builtin::NumberPredicate),
    ("boolean?", Builtin::BooleanPredicate),
    ("pair?", Builtin::PairPredicate),
    ("symbol?", Builtin::SymbolPredicate),
    ("apply", Builtin::Apply),
    ("call/cc", Builtin::CallCc),
];
