use super::model::{Builtin, Env, EnvRef, Value};

pub(super) fn initial_env() -> EnvRef {
    let env = Env::new(None);

    for builtin in [
        Builtin::Add,
        Builtin::Sub,
        Builtin::Mul,
        Builtin::Div,
        Builtin::Abs,
        Builtin::Modulo,
        Builtin::Remainder,
        Builtin::Quotient,
        Builtin::Gcd,
        Builtin::Lcm,
        Builtin::Min,
        Builtin::Max,
        Builtin::Expt,
        Builtin::Truncate,
        Builtin::Round,
        Builtin::ZeroPred,
        Builtin::PositivePred,
        Builtin::NegativePred,
        Builtin::OddPred,
        Builtin::EvenPred,
        Builtin::ExactPred,
        Builtin::InexactPred,
        Builtin::IntegerPred,
        Builtin::RationalPred,
        Builtin::ExactToInexact,
        Builtin::InexactToExact,
        Builtin::Numerator,
        Builtin::Denominator,
        Builtin::Less,
        Builtin::Greater,
        Builtin::Equal,
        Builtin::LessEqual,
        Builtin::GreaterEqual,
        Builtin::EqPred,
        Builtin::EqvPred,
        Builtin::EqualPred,
        Builtin::Not,
        Builtin::Display,
        Builtin::Write,
        Builtin::Newline,
        Builtin::Cons,
        Builtin::Car,
        Builtin::Cdr,
        Builtin::Cddr,
        Builtin::SetCar,
        Builtin::SetCdr,
        Builtin::Append,
        Builtin::Reverse,
        Builtin::List,
        Builtin::Length,
        Builtin::ListRef,
        Builtin::ListTail,
        Builtin::ListPred,
        Builtin::Memq,
        Builtin::Memv,
        Builtin::Member,
        Builtin::Vector,
        Builtin::MakeVector,
        Builtin::VectorRef,
        Builtin::VectorSet,
        Builtin::VectorLength,
        Builtin::VectorPred,
        Builtin::VectorToList,
        Builtin::ListToVector,
        Builtin::Assq,
        Builtin::Assoc,
        Builtin::Assv,
        Builtin::Map,
        Builtin::ForEach,
        Builtin::MakeString,
        Builtin::String,
        Builtin::StringAppend,
        Builtin::StringLength,
        Builtin::Substring,
        Builtin::StringToNumber,
        Builtin::NumberToString,
        Builtin::SymbolToString,
        Builtin::StringToSymbol,
        Builtin::StringRef,
        Builtin::StringSet,
        Builtin::StringCopy,
        Builtin::StringToList,
        Builtin::ListToString,
        Builtin::NullPred,
        Builtin::NumberPred,
        Builtin::StringPred,
        Builtin::BooleanPred,
        Builtin::ProcedurePred,
        Builtin::PairPred,
        Builtin::SymbolPred,
        Builtin::CharPred,
        Builtin::CharAlphabeticPred,
        Builtin::CharNumericPred,
        Builtin::CharToInteger,
        Builtin::IntegerToChar,
        Builtin::CharUpcase,
        Builtin::CharDowncase,
        Builtin::CharEqual,
        Builtin::CharLess,
        Builtin::StringEqual,
        Builtin::StringLess,
        Builtin::StringGreater,
        Builtin::StringLessEqual,
        Builtin::StringGreaterEqual,
        Builtin::StringCiEqual,
        Builtin::StringUpcase,
        Builtin::StringDowncase,
        Builtin::Error,
        Builtin::Raise,
        Builtin::WithExceptionHandler,
        Builtin::DynamicWind,
        Builtin::Values,
        Builtin::CallWithValues,
        Builtin::Apply,
        Builtin::CallCc,
    ] {
        env.define(builtin.name().into(), Value::Builtin(builtin));
    }

    let call_cc = env
        .lookup_cell("call/cc")
        .expect("call/cc is defined in the initial environment");
    env.define_alias("call-with-current-continuation".into(), call_cc);

    env
}
