package ming

private[ming] object BuiltinRegistry:

  val builtinNames: List[String] = List(
    "+",
    "-",
    "*",
    "/",
    "<",
    ">",
    "=",
    "<=",
    ">=",
    "not",
    "cons",
    "car",
    "cdr",
    "caar",
    "cadr",
    "cdar",
    "cddr",
    "null?",
    "list",
    "length",
    "number?",
    "string?",
    "boolean?",
    "pair?",
    "symbol?",
    "append",
    "display",
    "write",
    "newline",
    "string-append",
    "string-length",
    "substring",
    "string->number",
    "number->string",
    "symbol->string",
    "string->symbol",
    "string-ref",
    "string-set!",
    "string-copy",
    "char?",
    "apply",
    "abs",
    "modulo",
    "remainder",
    "quotient",
    "min",
    "max",
    "expt",
    "zero?",
    "positive?",
    "negative?",
    "odd?",
    "even?",
    "list-ref",
    "list-tail",
    "list?",
    "assoc",
    "map",
    "for-each",
    "eq?",
    "equal?",
    "char-alphabetic?",
    "char-numeric?",
    "char-upcase",
    "char-downcase",
    "char=?",
    "char<?",
    "string=?",
    "string<?",
    "string-ci=?",
    "string-upcase",
    "string-downcase",
    "exact?",
    "inexact?",
    "integer?",
    "rational?",
    "exact->inexact",
    "inexact->exact",
    "numerator",
    "denominator",
    "procedure?",
    "eqv?",
    "vector",
    "make-vector",
    "vector-ref",
    "vector-set!",
    "vector-length",
    "vector?",
    "vector->list",
    "list->vector",
    "string->list",
    "list->string",
    "char->integer",
    "integer->char",
    "make-string",
    "string",
    "set-car!",
    "set-cdr!",
    "reverse",
    "member",
    "memv",
    "assv",
    "memq",
    "assq",
    "gcd",
    "lcm",
    "floor",
    "ceiling",
    "truncate",
    "round",
    "sqrt",
    "char<=?",
    "char>=?",
    "char>?",
    "string<=?",
    "string>=?",
    "string>?",
    "void"
  )

  def makeTopLevelEnv(): Env =
    val env = Env(scala.collection.mutable.Map.empty, None)
    for name <- builtinNames do env.define(name, Expr.Sym(name))
    env

  def isProcedure(e: Expr): Expr = e match
    case Expr.Lambda(_, _, _, _) | Expr.CaseLambda(_, _) => Expr.Bool(true)
    case Expr.Sym(n) if builtinNames.contains(n)         => Expr.Bool(true)
    case _                                               => Expr.Bool(false)
