#![cfg_attr(feature = "quality-gate", deny(warnings))]
#![cfg_attr(feature = "quality-gate", deny(clippy::unwrap_used))]
#![cfg_attr(feature = "quality-gate", deny(clippy::result_unit_err))]
#![cfg_attr(feature = "quality-gate", deny(clippy::manual_assert))]
#![cfg_attr(feature = "quality-gate", warn(clippy::too_many_lines))]
#![cfg_attr(feature = "quality-gate", warn(clippy::excessive_nesting))]
#![cfg_attr(feature = "quality-gate", warn(clippy::manual_filter_map))]
#![cfg_attr(feature = "quality-gate", warn(clippy::manual_find_map))]
#![cfg_attr(feature = "quality-gate", warn(clippy::manual_flatten))]
#![cfg_attr(feature = "quality-gate", warn(clippy::manual_try_fold))]
#![cfg_attr(feature = "quality-gate", warn(clippy::manual_let_else))]
#![cfg_attr(feature = "quality-gate", warn(clippy::needless_range_loop))]
#![cfg_attr(feature = "quality-gate", warn(clippy::explicit_counter_loop))]
#![cfg_attr(feature = "quality-gate", warn(clippy::explicit_iter_loop))]
#![cfg_attr(feature = "quality-gate", warn(clippy::vec_init_then_push))]
#![cfg_attr(feature = "quality-gate", warn(clippy::needless_collect))]
#![cfg_attr(feature = "quality-gate", warn(clippy::uninlined_format_args))]

pub mod scheme;
