//! Build script: generates Rust test functions from bench/tests.json.
//!
//! This makes tests.json the single source of truth for test definitions.
//! Adding a test to tests.json automatically creates a corresponding #[test] fn.

use serde::Deserialize;
use std::fs;
use std::io::Write;
use std::path::Path;

const WRITE_ERROR: &str = "generated tests file should remain writable";

macro_rules! line {
    ($out:expr) => {
        writeln!($out).expect(WRITE_ERROR)
    };
    ($out:expr, $($arg:tt)*) => {
        writeln!($out, $($arg)*).expect(WRITE_ERROR)
    };
}

#[derive(Deserialize)]
struct TestEntry {
    name: String,
    level: u32,
    fixture: String,
    kind: String,
    #[serde(default)]
    expected: Option<String>,
    #[serde(default)]
    expected_output: Option<String>,
    #[serde(default)]
    deprecated_after: Option<u32>,
}

fn main() {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("Cargo should set CARGO_MANIFEST_DIR");
    let tests_json_path = Path::new(&manifest_dir).join("../tests.json");
    let out_dir = std::env::var("OUT_DIR").expect("Cargo should set OUT_DIR");
    let out_path = Path::new(&out_dir).join("tests_generated.rs");

    println!("cargo:rerun-if-changed=../tests.json");
    println!("cargo:rerun-if-changed=../fixtures");

    let json = fs::read_to_string(&tests_json_path)
        .unwrap_or_else(|e| panic!("Cannot read {}: {e}", tests_json_path.display()));
    let tests: Vec<TestEntry> =
        serde_json::from_str(&json).unwrap_or_else(|e| panic!("Cannot parse tests.json: {e}"));
    let mut out = fs::File::create(&out_path)
        .unwrap_or_else(|e| panic!("Cannot create {}: {e}", out_path.display()));

    line!(
        out,
        "// AUTO-GENERATED by build.rs from tests.json — do not edit"
    );
    line!(out, "// {} tests across {} levels", tests.len(), {
        let mut levels: Vec<u32> = tests.iter().map(|t| t.level).collect();
        levels.sort();
        levels.dedup();
        levels.len()
    });
    line!(out);
    line!(out, "use crate::scheme::eval_str;");
    line!(out);

    let needs_output = tests.iter().any(|t| t.kind == "eval_str_with_output");
    if needs_output {
        line!(out, "#[allow(unused_imports)]");
        line!(out, "use crate::scheme::eval_str_with_output;");
        line!(out);
    }

    let needs_position = tests.iter().any(|t| t.kind == "eval_str_err_with_position");
    if needs_position {
        line!(out, "fn has_position_info(msg: &str) -> bool {{");
        line!(
            out,
            "    msg.as_bytes().windows(2).any(|w| w[0].is_ascii_digit() && w[1] == b':')"
        );
        line!(out, "}}");
        line!(out);
    }

    let needs_deprecated = tests.iter().any(|t| t.deprecated_after.is_some());
    if needs_deprecated {
        line!(out, "fn current_bench_level() -> u32 {{");
        line!(out, "    std::env::var(\"BENCH_LEVEL\").ok().and_then(|v| v.parse().ok()).unwrap_or(u32::MAX)");
        line!(out, "}}");
        line!(out);
    }

    let fixtures_abs = Path::new(&manifest_dir)
        .join("../fixtures")
        .canonicalize()
        .unwrap_or_else(|e| panic!("Cannot resolve fixtures dir: {e}"));

    for test in &tests {
        let fn_name = test.name.replace('-', "_");
        let fixture_path = fixtures_abs.join(&test.fixture);
        let fixture_path_str = fixture_path.display();

        line!(out, "#[test]");
        line!(out, "fn test_{fn_name}() {{");

        if let Some(after) = test.deprecated_after {
            line!(out, "    if current_bench_level() > {after} {{ return; }}");
        }

        match test.kind.as_str() {
            "eval_str_ok" => {
                let expected = test.expected.as_deref().unwrap_or("");
                let escaped = expected.replace('\\', "\\\\").replace('"', "\\\"");
                line!(out, "    assert_eq!(");
                line!(
                    out,
                    "        eval_str(include_str!(\"{fixture_path_str}\").trim()),"
                );
                line!(out, "        Ok(\"{escaped}\".into())");
                line!(out, "    );");
            }
            "eval_str_err" => {
                line!(out, "    assert!(");
                line!(
                    out,
                    "        eval_str(include_str!(\"{fixture_path_str}\").trim()).is_err(),"
                );
                line!(out, "        \"expected error for {}\"", test.name);
                line!(out, "    );");
            }
            "eval_str_err_with_position" => {
                line!(out, "    let err = eval_str(include_str!(\"{fixture_path_str}\").trim()).expect_err(\"fixture should fail\");");
                line!(out, "    assert!(");
                line!(out, "        has_position_info(&err.to_string()),");
                line!(
                    out,
                    "        \"error should contain position info: {{err}}\""
                );
                line!(out, "    );");
            }
            "eval_str_with_output" => {
                let expected_output = test.expected_output.as_deref().unwrap_or("");
                let escaped = expected_output
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n");
                line!(out, "    let (_, output) = eval_str_with_output(include_str!(\"{fixture_path_str}\").trim()).expect(\"fixture should evaluate successfully\");");
                line!(out, "    assert_eq!(output, \"{escaped}\");");
            }
            other => {
                line!(out, "    // Unknown test kind: {other}");
                line!(
                    out,
                    "    unimplemented!(\"test kind '{}' not supported\");",
                    other
                );
            }
        }

        line!(out, "}}");
        line!(out);
    }
}
