/// Build script: generates Rust test functions from bench/tests.json.
///
/// This makes tests.json the single source of truth for test definitions.
/// Adding a test to tests.json automatically creates a corresponding #[test] fn.
use serde::Deserialize;
use std::fs;
use std::io::Write;
use std::path::Path;

#[derive(Deserialize)]
struct TestEntry {
    name: String,
    level: u32,
    fixture: String,
    kind: String,
    #[serde(default)]
    expected: Option<String>,
    #[serde(default)]
    expected_output: Option<String>,
    #[serde(default)]
    deprecated_after: Option<u32>,
}

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let tests_json_path = Path::new(&manifest_dir).join("../tests.json");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("tests_generated.rs");

    // Tell cargo to rerun if tests.json changes
    println!("cargo:rerun-if-changed=../tests.json");
    // Also rerun if any fixture changes
    println!("cargo:rerun-if-changed=../fixtures");

    let json = fs::read_to_string(&tests_json_path)
        .unwrap_or_else(|e| panic!("Cannot read {}: {e}", tests_json_path.display()));
    let tests: Vec<TestEntry> =
        serde_json::from_str(&json).unwrap_or_else(|e| panic!("Cannot parse tests.json: {e}"));

    let mut out = fs::File::create(&out_path)
        .unwrap_or_else(|e| panic!("Cannot create {}: {e}", out_path.display()));

    writeln!(out, "// AUTO-GENERATED by build.rs from tests.json — do not edit").expect("write");
    writeln!(out, "// {} tests across {} levels", tests.len(), {
        let mut levels: Vec<u32> = tests.iter().map(|t| t.level).collect();
        levels.sort();
        levels.dedup();
        levels.len()
    }).expect("write");
    writeln!(out).expect("write");
    writeln!(out, "use crate::scheme::eval_str;").expect("write");
    writeln!(out).expect("write");

    // Check if any test uses eval_str_with_output
    let needs_output = tests.iter().any(|t| t.kind == "eval_str_with_output");
    if needs_output {
        writeln!(out, "#[allow(unused_imports)]").expect("write");
        writeln!(out, "use crate::scheme::eval_str_with_output;").expect("write");
        writeln!(out).expect("write");
    }

    // Helper function for position checking (used by eval_str_err_with_position)
    let needs_position = tests.iter().any(|t| t.kind == "eval_str_err_with_position");
    if needs_position {
        writeln!(out, "fn has_position_info(msg: &str) -> bool {{").expect("write");
        writeln!(out, "    msg.as_bytes().windows(2).any(|w| w[0].is_ascii_digit() && w[1] == b':')").expect("write");
        writeln!(out, "}}").expect("write");
        writeln!(out).expect("write");
    }

    // Helper for deprecated level checking
    let needs_deprecated = tests.iter().any(|t| t.deprecated_after.is_some());
    if needs_deprecated {
        writeln!(out, "fn current_bench_level() -> u32 {{").expect("write");
        writeln!(out, "    std::env::var(\"BENCH_LEVEL\").ok().and_then(|v| v.parse().ok()).unwrap_or(u32::MAX)").expect("write");
        writeln!(out, "}}").expect("write");
        writeln!(out).expect("write");
    }

    // Compute absolute path to fixtures dir for include_str!()
    let fixtures_abs = Path::new(&manifest_dir)
        .join("../fixtures")
        .canonicalize()
        .unwrap_or_else(|e| panic!("Cannot resolve fixtures dir: {e}"));

    // Generate one #[test] fn per entry
    for test in &tests {
        let fn_name = test.name.replace('-', "_");
        let fixture_path = fixtures_abs.join(&test.fixture);
        let fixture_path_str = fixture_path.display();

        writeln!(out, "#[test]").expect("write");
        writeln!(out, "fn test_{fn_name}() {{").expect("write");

        // Deprecated check
        if let Some(after) = test.deprecated_after {
            writeln!(out, "    if current_bench_level() > {after} {{ return; }}").expect("write");
        }

        match test.kind.as_str() {
            "eval_str_ok" => {
                let expected = test.expected.as_deref().unwrap_or("");
                let escaped = expected.replace('\\', "\\\\").replace('"', "\\\"");
                writeln!(out, "    assert_eq!(").expect("write");
                writeln!(out, "        eval_str(include_str!(\"{fixture_path_str}\").trim()),").expect("write");
                writeln!(out, "        Ok(\"{escaped}\".into())").expect("write");
                writeln!(out, "    );").expect("write");
            }
            "eval_str_err" => {
                writeln!(out, "    assert!(").expect("write");
                writeln!(out, "        eval_str(include_str!(\"{fixture_path_str}\").trim()).is_err(),").expect("write");
                writeln!(out, "        \"expected error for {}\"", test.name).expect("write");
                writeln!(out, "    );").expect("write");
            }
            "eval_str_err_with_position" => {
                writeln!(out, "    let err = eval_str(include_str!(\"{fixture_path_str}\").trim()).unwrap_err();").expect("write");
                writeln!(out, "    assert!(").expect("write");
                writeln!(out, "        has_position_info(&err.to_string()),").expect("write");
                writeln!(out, "        \"error should contain position info: {{err}}\"").expect("write");
                writeln!(out, "    );").expect("write");
            }
            "eval_str_with_output" => {
                let expected_output = test.expected_output.as_deref().unwrap_or("");
                let escaped = expected_output.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n");
                writeln!(out, "    let (_, output) = eval_str_with_output(include_str!(\"{fixture_path_str}\").trim()).unwrap();").expect("write");
                writeln!(out, "    assert_eq!(output, \"{escaped}\");").expect("write");
            }
            other => {
                writeln!(out, "    // Unknown test kind: {other}").expect("write");
                writeln!(out, "    unimplemented!(\"test kind '{}' not supported\");", other).expect("write");
            }
        }

        writeln!(out, "}}").expect("write");
        writeln!(out).expect("write");
    }
}
