/// Build script: generates Rust test functions from bench/tests.json.
///
/// This makes tests.json the single source of truth for test definitions.
/// Adding a test to tests.json automatically creates a corresponding #[test] fn.
use serde::Deserialize;
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

#[derive(Deserialize)]
struct TestEntry {
    name: String,
    level: u32,
    fixture: String,
    kind: String,
    #[serde(default)]
    expected: Option<String>,
    #[serde(default)]
    expected_output: Option<String>,
    #[serde(default)]
    deprecated_after: Option<u32>,
}

fn main() -> io::Result<()> {
    emit_rerun_instructions();

    let manifest_dir = env_var("CARGO_MANIFEST_DIR")?;
    let out_dir = env_var("OUT_DIR")?;
    let tests_json_path = Path::new(&manifest_dir).join("../tests.json");
    let out_path = Path::new(&out_dir).join("tests_generated.rs");
    let tests = load_tests(&tests_json_path)?;
    let fixtures_dir = resolve_fixtures_dir(&manifest_dir)?;
    let mut out = create_output_file(&out_path)?;

    write_prelude(&mut out, &tests)?;
    for test in &tests {
        write_test(&mut out, test, &fixtures_dir)?;
    }

    Ok(())
}

fn emit_rerun_instructions() {
    println!("cargo:rerun-if-changed=../tests.json");
    println!("cargo:rerun-if-changed=../fixtures");
}

fn env_var(name: &'static str) -> io::Result<String> {
    std::env::var(name).map_err(|source| io::Error::other(format!("missing {name}: {source}")))
}

fn load_tests(path: &Path) -> io::Result<Vec<TestEntry>> {
    let json = fs::read_to_string(path)
        .map_err(|source| io::Error::other(format!("cannot read {}: {source}", path.display())))?;

    serde_json::from_str(&json)
        .map_err(|source| io::Error::other(format!("cannot parse {}: {source}", path.display())))
}

fn resolve_fixtures_dir(manifest_dir: &str) -> io::Result<PathBuf> {
    let fixtures_dir = Path::new(manifest_dir).join("../fixtures");
    fixtures_dir.canonicalize().map_err(|source| {
        io::Error::other(format!(
            "cannot resolve fixtures dir {}: {source}",
            fixtures_dir.display()
        ))
    })
}

fn create_output_file(path: &Path) -> io::Result<fs::File> {
    fs::File::create(path)
        .map_err(|source| io::Error::other(format!("cannot create {}: {source}", path.display())))
}

fn write_prelude(out: &mut impl Write, tests: &[TestEntry]) -> io::Result<()> {
    emit_line(
        out,
        "// AUTO-GENERATED by build.rs from tests.json — do not edit",
    )?;
    emit_line(
        out,
        format!(
            "// {} tests across {} levels",
            tests.len(),
            unique_level_count(tests)
        ),
    )?;
    emit_blank_line(out)?;
    emit_line(out, "use crate::scheme::eval_str;")?;
    emit_blank_line(out)?;

    if tests.iter().any(|test| test.kind == "eval_str_with_output") {
        emit_line(out, "#[allow(unused_imports)]")?;
        emit_line(out, "use crate::scheme::eval_str_with_output;")?;
        emit_blank_line(out)?;
    }

    if tests
        .iter()
        .any(|test| test.kind == "eval_str_err_with_position")
    {
        emit_position_helper(out)?;
    }

    if tests.iter().any(|test| test.deprecated_after.is_some()) {
        emit_deprecated_helper(out)?;
    }

    Ok(())
}

fn unique_level_count(tests: &[TestEntry]) -> usize {
    let mut levels: Vec<u32> = tests.iter().map(|test| test.level).collect();
    levels.sort();
    levels.dedup();
    levels.len()
}

fn emit_position_helper(out: &mut impl Write) -> io::Result<()> {
    emit_line(out, "fn has_position_info(msg: &str) -> bool {")?;
    emit_line(
        out,
        "    msg.as_bytes().windows(2).any(|w| w[0].is_ascii_digit() && w[1] == b':')",
    )?;
    emit_line(out, "}")?;
    emit_blank_line(out)
}

fn emit_deprecated_helper(out: &mut impl Write) -> io::Result<()> {
    emit_line(out, "fn current_bench_level() -> u32 {")?;
    emit_line(
        out,
        "    let Ok(value) = std::env::var(\"BENCH_LEVEL\") else {",
    )?;
    emit_line(out, "        return u32::MAX;")?;
    emit_line(out, "    };")?;
    emit_line(out, "    match value.parse::<u32>() {")?;
    emit_line(out, "        Ok(level) => level,")?;
    emit_line(out, "        Err(_) => u32::MAX,")?;
    emit_line(out, "    }")?;
    emit_line(out, "}")?;
    emit_blank_line(out)
}

fn write_test(out: &mut impl Write, test: &TestEntry, fixtures_dir: &Path) -> io::Result<()> {
    let fn_name = test.name.replace('-', "_");
    let fixture_path = fixtures_dir.join(&test.fixture);
    let fixture_expr = fixture_expr(&fixture_path);

    emit_line(out, "#[test]")?;
    emit_line(out, format!("fn test_{fn_name}() {{"))?;

    if let Some(after) = test.deprecated_after {
        emit_line(
            out,
            format!("    if current_bench_level() > {after} {{ return; }}"),
        )?;
    }

    write_test_body(out, test, &fixture_expr)?;
    emit_line(out, "}")?;
    emit_blank_line(out)
}

fn write_test_body(out: &mut impl Write, test: &TestEntry, fixture_expr: &str) -> io::Result<()> {
    match test.kind.as_str() {
        "eval_str_ok" => {
            write_eval_str_ok_test(out, test.expected.as_deref().unwrap_or(""), fixture_expr)
        }
        "eval_str_err" => write_eval_str_err_test(out, &test.name, fixture_expr),
        "eval_str_err_with_position" => write_eval_str_err_with_position_test(out, fixture_expr),
        "eval_str_with_output" => write_eval_str_with_output_test(
            out,
            test.expected_output.as_deref().unwrap_or(""),
            fixture_expr,
        ),
        other => write_unknown_test_kind(out, other),
    }
}

fn write_eval_str_ok_test(
    out: &mut impl Write,
    expected: &str,
    fixture_expr: &str,
) -> io::Result<()> {
    let expected = escape_rust_string(expected);
    emit_line(out, "    assert_eq!(")?;
    emit_line(out, format!("        eval_str({fixture_expr}),"))?;
    emit_line(out, format!("        Ok(\"{expected}\".into())"))?;
    emit_line(out, "    );")
}

fn write_eval_str_err_test(
    out: &mut impl Write,
    test_name: &str,
    fixture_expr: &str,
) -> io::Result<()> {
    emit_line(out, "    assert!(")?;
    emit_line(out, format!("        eval_str({fixture_expr}).is_err(),"))?;
    emit_line(
        out,
        format!(
            "        \"expected error for {}\"",
            escape_rust_string(test_name)
        ),
    )?;
    emit_line(out, "    );")
}

fn write_eval_str_err_with_position_test(
    out: &mut impl Write,
    fixture_expr: &str,
) -> io::Result<()> {
    emit_line(
        out,
        format!(
            "    let err = eval_str({fixture_expr}).expect_err(\"fixture should fail with position info\");"
        ),
    )?;
    emit_line(out, "    assert!(")?;
    emit_line(out, "        has_position_info(&err.to_string()),")?;
    emit_line(out, "        \"error should contain position info: {err}\"")?;
    emit_line(out, "    );")
}

fn write_eval_str_with_output_test(
    out: &mut impl Write,
    expected_output: &str,
    fixture_expr: &str,
) -> io::Result<()> {
    let expected_output = escape_rust_string(expected_output);
    emit_line(
        out,
        format!(
            "    let (_, output) = eval_str_with_output({fixture_expr}).expect(\"fixture should evaluate with output\");"
        ),
    )?;
    emit_line(
        out,
        format!("    assert_eq!(output, \"{expected_output}\");"),
    )
}

fn write_unknown_test_kind(out: &mut impl Write, other: &str) -> io::Result<()> {
    let other = escape_rust_string(other);
    emit_line(out, format!("    // Unknown test kind: {other}"))?;
    emit_line(
        out,
        format!(
            "    unimplemented!(\"test kind '{}' not supported\");",
            other
        ),
    )
}

fn fixture_expr(path: &Path) -> String {
    let escaped_path = escape_rust_string(&path.display().to_string());
    format!("include_str!(\"{escaped_path}\").trim()")
}

fn escape_rust_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            _ => escaped.push(ch),
        }
    }
    escaped
}

fn emit_line(out: &mut impl Write, line: impl std::fmt::Display) -> io::Result<()> {
    writeln!(out, "{line}")
}

fn emit_blank_line(out: &mut impl Write) -> io::Result<()> {
    writeln!(out)
}
